#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: examplevol-ex
#spec:
#  storageClassName: rook-block
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: 20Gi
#---
apiVersion: v1
kind: Pod
metadata:
  name: vol-pod-ex
spec:
  securityContext:
    fsGroup: 100
  containers:
  - name: vol-container-ex
    image: gitlab-registry.nautilus.optiputer.net/prp/jupyterlab
    #args: ["sleep", "36500000"]
    volumeMounts:
    - mountPath: /examplevol-ex
      name: examplevol-ex
      spec:
    resources:
      limits:
        memory: "64Gi"
        cpu: 4
        #nvidia.com/gpu: 1
      requests:
        cpu: 4
        #nvidia.com/gpu: 1
        memory: "32Gi"
    #command: ["stress"]
    #args: ["python", "/home/jovyan/testCases/algoTrial.py"]
    args: ["sleep", "36500000"]
  restartPolicy: Never
  volumes:
    - name: examplevol-ex
      persistentVolumeClaim:
        claimName: examplevol-ex
